server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5456/postgres
    username: root
    password: pass
  liquibase:
    change-log: db/changelog-master.xml
    enabled: true
